= Bewirb dich!

Lieber zukünftiger Developer-Gepard!
Als Software-Developer ist es ja zu einfach, einfach nur ein Bewerbungs-Formular auszufüllen.
Wir suchen DICH, wenn du deine Komfortzone verlassen und unser Rudel verstärken willst.

Deshalb haben wir eine kleine technische Herausforderung für dich - ein REST Service, über das du uns deine Bewerbung schickst.

Ich freue mich auf deinen REST-Call ;)

Michael

== REST Endpoints

=== List available challenges

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
[
  {
    "id": 1,
    "question": "..."
  }
]
----

=== Challenge by id

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "id": 1,
   "question": "1 Notebook und eine ..."
}
----

==== Error Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "message": "...",
   "success": false
}
----

=== Answer challenge

`POST https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>/answer` +

.Request-Headers

[source]
----
Content-Type: application/json
----

.Request-Body
[source,json]
----
{
   "jobId": "<JOB_ID_THE_APPLICATION_IS_FOR>",
   "firstName": "<YOUR_FIRST_NAME>",
   "lastName": "<YOUR_LASTNAME>",
   "email": "<YOUR_EMAIL>",
   "answer": "<YOUR_ANSWER>",
   "source": "<YOUR_SOURCE_WHERE_YOU_HEARD_FROM_US>",
   "messageToGepardec": "<WHY_GEPARDEC_?>",
   "otherSource": "<OPTIONLA_IF_SOURCE_NOT_SET_TO__MESSEN_MEETUPS_EMPFEHLUNG_SONSTIGE>",
   "title": "<OPTIONAL_YOUR_TITLE>",
   "phone": "<OPTIONAL_YOUR_PHONE>",
   "linkedInLink": "<OPTIONAL_YOUR_LINKEDIN_LINK>",
   "xingLink": "<OPTIONAL_YOUR_XING_LINK>",
   "cv": "<OPTIONAL_YOUR_CV_IN_BASE64>"
}
----

TIP: See link:src/main/java/com/gepardec/wdg/client/personio/Source.java[Source.java] for possible enum values (Use the enum name). +
     Your CV must be a file encoded in Base64.

==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Danke! Du hast den Geparden in dir erweckt und wir melden uns in den nächsten Tagen bei dir! Lg, Michael Sollberger",
   "success": true
}
----

==== Constraint Violation Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "The request was invalid due to constraint violations",
   "success": false,
   "violations" : [
        "..."
   ]
}
----

==== E-Mail already used for an application

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "The used email address has already been used for an application",
   "success": false
}
----

==== Invalid Answer Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Sorry, die Antwort ist falsch. Denk' nochmal in Ruhe darüber nach und versuch es noch einmal.",
   "success": false
}
----

== Developer documentation for setting up this project itself (not necessary for applicants)

=== Preparations

Sensitive configurations have been externalized and must be added before starting the development.
Place the following file in the ``/config`` directory.

.application.properties
[source,properties]
----
## Perosnio configurations
personio.company_id=<COMPANY_ID>
personio.access_token=<ACCESS_TOKEN>
# MP-Rest-Client properties
personio/mp-rest/url=https://api.personio.de
# Opentracing/Jaeger configuration
quarkus.jaeger.enabled=true
quarkus.jaeger.service-name=weckdengeparden
quarkus.jaeger.agent-host-port=<AGENT_HOST_PORT>
quarkus.jaeger.reporter-log-spans=<TRUE_IF_SPAN_SHALL_BE_LOGGED>
quarkus.jaeger.sampler-type=<SAMPLE_TYPE>
quarkus.jaeger.sampler-param=<SAMPLE_PARAM>
quarkus.jaeger.reporter-max-queue-size=<SPAN_QUEUE_SIZE>
quarkus.jaeger.reporter-flush-interval=<FLUSH_DURATION_EG_1.500S>
----

TIP: See link:https://quarkus.io/guides/opentracing[quarkus-opentracing]

=== Build the application

Build the application with the following command

.Build the uber jar
[source,bash]
----
mvn clean install -Dpackage.uber.jar=true
----

== Openshift

In this section you see how to setup an Openshift project which hosts the ``weckdengeparden`` service.

=== Preparations

Ensure you have setup up your development environment and that you have built the application.

=== Setup

Execute all commands in the root directory of this project. Ensure that your are logged into the proper Openshift project.

.Jaeger Services
[source,bash]
----
# Create jaeger services
oc process -f templates/jaeger.yaml -o yaml  | oc apply -f -

# Delete jaeger services
oc process -f templates/jaeger.yaml -o yaml  | oc delete -f -
----

.Secrets
[source,bash]
----
# Create secret for weckdengeparden
oc create secret generic weckdengeparden --from-file=application.properties=config/application.properties
----

.Build Configuration
[source,bash]
----
# Binary build for uber jar
oc new-build --binary=true --name=weckdengeparden --docker-image=docker.io/fabric8/s2i-java:3.0-java11
oc set triggers bc/weckdengeparden --remove-all
----

.Template
[source,bash]
----
# Create service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden.properties | oc create -f -

# Delete service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden.properties | oc delete -f -
----

=== Deploy application

.Build Configuration
[source,bash]
----
# Start build with local binary
oc start-build weckdengeparden --from-file=target/wdg-0.0.1-runner.jar --follow --wait
----

== Tracing

The services calls are traced with opentracing and can be analysed with Jaeger you can reach link:https://jaeger-query-57-services.cloud.itandtel.at/[here].
