= Bewirb dich!

Lieber zukünftiger Developer-Gepard!
Als Software-Developer ist es ja zu einfach, einfach nur ein Bewerbungs-Formular auszufüllen.
Wir suchen DICH, wenn du deine Komfortzone verlassen und unser Rudel verstärken willst.

Deshalb haben wir eine kleine technische Herausforderung für dich - ein REST Service, über das du uns deine Bewerbung schickst.

Wichtig für uns: Was kann dein Beitrag zur Umsetzung der link:https://www.gepardec.com/arbeit-kultur/werte-und-kultur/[Vision] von Gepardec sein? 
Bitte beantworte das in der "messageToGepardec".

Ich freue mich auf deinen REST-Call ;)

Michael

== REST Endpoints

=== List available challenges

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
[
  {
    "id": 1,
    "question": "..."
  }
]
----

=== Challenge by id

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "id": 1,
   "question": "1 Notebook und eine ..."
}
----

==== Error Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "message": "...",
   "success": false
}
----

=== Answer challenge

`POST https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>/answer` +

.Request-Headers

[source]
----
Content-Type: application/json
----

.Request-Body
[source,json]
----
{
   "jobId": "<JOB_ID_THE_APPLICATION_IS_FOR>",
   "firstName": "<YOUR_FIRST_NAME>",
   "lastName": "<YOUR_LASTNAME>",
   "email": "<YOUR_EMAIL>",
   "answer": "<YOUR_ANSWER>",
   "source": "<YOUR_SOURCE_WHERE_YOU_HEARD_FROM_US>",
   "messageToGepardec": "<Was kann dein Beitrag zur Umsetzung der Vision von gepardec sein?>",
   "otherSource": "<OPTIONAL_IF_SOURCE_NOT_SET_TO__MESSEN_MEETUPS_EMPFEHLUNG_SONSTIGE>",
   "title": "<OPTIONAL_YOUR_TITLE>",
   "phone": "<OPTIONAL_YOUR_PHONE>",
   "linkedInLink": "<OPTIONAL_YOUR_LINKEDIN_LINK>",
   "xingLink": "<OPTIONAL_YOUR_XING_LINK>",
   "cv": "<YOUR_CV_IN_BASE64>"
}
----

TIP: The possible enum values for the property ``source`` see link:src/main/java/com/gepardec/wdg/client/personio/Source.java[Source.java] (Use the enum name). +
     The property ``cv`` must be a file encoded in a Base64 String.

IMPORTANT: All field except `linkedInLink`, `xingLink`, `titel` and `phone` are required.

==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Danke! Du hast den Geparden in dir erweckt und wir melden uns in den nächsten Tagen bei dir! Lg, Michael Sollberger",
   "success": true
}
----

==== Constraint Violation Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "The request was invalid due to constraint violations",
   "success": false,
   "violations" : [
        "..."
   ]
}
----

==== E-Mail already used for an application

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "The used email address has already been used for an application",
   "success": false
}
----

==== Invalid Answer Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Sorry, die Antwort ist falsch. Denk' nochmal in Ruhe darüber nach und versuch es noch einmal.",
   "success": false
}
----

== Developer documentation for setting up this project itself (not necessary for applicants)

=== Preparations

Sensitive configurations have been externalized and must be added before starting the development. +
Place the following configuration file in the ``/config`` directory additionally to a truststore.jks which holds personio related trusted certificates.

.application.properties
[source,yaml]
----
quarkus:
  log:
    console:
      enable: true
      level: ALL
  jaeger:
    enabled: false
    service-name: "weckdengeparden"
    agent-host-port: "AGENT_HOST_PORT"
    reporter-log-spans: false
    sampler-type: "const"
    sampler-parameter: 1
    reporter-flush-interval: 1.500S
    reporter-max-queue-size: 200

personio:
  company_id: "COMPANY_ID"
  access_token: "ACCESS_TOKEN"

personio/mp-rest/url: "https://api.personio.de"
personio/mp-rest/trustStorePassword: "PWD_OF_TRUSTSTORE_FILE"
personio/mp-rest/trustStoreType: "TRUSTSTORE_TYPE"
personio/mp-rest/trustStore: "FQN_OF_TRUSTSTORE_FILE"
personio/mp-rest/scope: "javax.enterprise.context.RequestScoped"
----

TIP: See link:https://quarkus.io/guides/opentracing[quarkus-opentracing]

=== Build the application

Build the application with the following command

.Build the uber jar
[source,bash]
----
mvn clean install -Dpackage.uber.jar=true
----

== Openshift

In this section you see how to setup an Openshift project which hosts the ``weckdengeparden`` service.

=== Preparations

. Ensure you have setup up your development environment and that you have built the application.
. Ensure that you have an valid ``config/application.yml`` file
. Ensure you have a ``config/truststore.jks`` file which contains personio related trusted certificates

=== Setup

Execute all commands in the root directory of this project. Ensure that your are logged into the proper Openshift project.

.Jaeger Services
[source,bash]
----
# Create jaeger services
oc process -f templates/jaeger.yaml -o yaml  | oc apply -f -

# Delete jaeger services
oc process -f templates/jaeger.yaml -o yaml  | oc delete -f -
----

.Secrets
[source,bash]
----
# Create secret for weckdengeparden
oc create secret generic weckdengeparden \
   --from-file=application.yml=config/application-ocp.yml \
   --from-file=truststore.jks=config/truststore.jks
----

.Build Configuration
[source,bash]
----
# Binary build for uber jar
oc new-build --binary=true --name=weckdengeparden --docker-image=docker.io/fabric8/s2i-java:3.0-java11
oc set triggers bc/weckdengeparden --remove-all
----

.Template
[source,bash]
----
# Create service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden.properties | oc create -f -

# Delete service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden.properties | oc delete -f -
----

=== Deploy application

.Build Configuration
[source,bash]
----
# Start build with local binary
oc start-build weckdengeparden --from-file=target/wdg-1.0.0-runner.jar --follow --wait
----
