= weckdengeparden

Lieber zukünftiger Developer-Gepard!
Als Software-Developer ist es ja zu einfach, einfach nur ein Bewerbungs-Formular auszufüllen.
Wir suchen DICH, wenn du deine Komfortzone verlassen und unser Rudel verstärken willst.

Deshalb haben wir eine kleine technische Herausforderung für dich - ein REST Service, über das du uns deine Bewerbung schickst.

Ich freue mich auf deinen REST-Call ;)

Michael

== REST Endpoints

=== List available challenges

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
[
  {
    "id": 1,
    "question": "..."
  }
]
----

=== Challenge by id

`GET https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>` +


==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "id": 1,
   "question": "1 Notebook und eine ..."
}
----

==== Error Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Response-Body
[source,json]
----
{
   "message": "...",
   "success": false
}
----

=== Answer challenge

`POST https://weckdengeparden-57-services.cloud.itandtel.at/challenge/<CHALLENGE_ID>/answer` +

.Request-Headers

[source]
----
Content-Type: application/json
----

.Request-Body
[source,json]
----
{
   "firstName": "<YOUR_FIRST_NAME>",
   "lastName": "<YOUR_LASTNAME>",
   "email": "<YOUR_EMAIL>",
   "challengeAnswer": "<YOUR_ANSWER>",
   "title": "<OPTIONAL_YOUR_TITLE>",
   "phone": "<OPTIONAL_YOUR_PHONE>",
   "linkedInLink": "<OPTIONAL_YOUR_LINKEDIN_LINK>",
   "xingLink": "<OPTIONAL_YOUR_XING_LINK>",
   "source": "<OPTIONAL_SOURCE>",
   "cv": "<OPTIONAL_YOUR_CV_IN_BASE64>",
   "messageToGepardec": "<OPTIONAL_YOUR_MESSAGE_TO_GEPARDEC>"
}
----

TIP: See link:src/main/java/com/gepardec/wdg/client/personio/Source[Source.java] for possible enum values. +
     Your CV must be a file encoded in Base64.

==== Success Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Danke! Du hast den Geparden in dir erweckt und wir melden uns in den nächsten Tagen bei dir! Lg, Michael Sollberger",
   "success": true
}
----

==== Constraint Violation Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "The request was invalid due to constraint violations",
   "success": false,
   "violations" : [
        "..."
   ]
}
----

==== Invalid Answer Response

.Response-Headers
[source]
----
Content-Type: application/json
----

.Success Response-Body
[source]
----
{
   "message": "Sorry, die Antwort ist falsch. Denk' nochmal in Ruhe darüber nach und versuch es noch einmal.",
   "success": false
}
----

== Developer documentation for setting up this project itself (not necessary for applicants)

=== Preparations

Sensitive configurations have been externalized and must be added before starting the development.
Place the following file in the ``/config`` directory.

.application.properties
[source,properties]
----
## Perosnio configurations
personio.company.id=<COMPANY_ID>
personio.access.token=<ACCESS_TOKEN>
# MP-Rest-Client properties
personio/mp-rest/url=https://api.personio.de
----

=== Build the application

Build the application with the following command

.Build the uber jar
[source,bash]
----
mvn clean install -Dquarkus.package.uber.jar=true
----

== Openshift

In this section you see how to setup an Openshift project which hosts the ``weckdengeparden`` service.

=== Preparations

Ensure you have setup up your development environment and that you have built the application.

=== Setup

Execute all commands in the root directory of this project.

.Secrets
[source,bash]
----
# Create secret for weckdengeparden
oc create secret generic weckdengeparden --from-file=application.properties=config/application.properties -n 57-services
----

.Build Configuration
[source,bash]
----
# Binary build for uber jar
oc new-build --binary=true --name=weckdengeparden --docker-image=docker.io/fabric8/s2i-java:3.0-java11 -n 57-services
oc set triggers bc/weckdengeparden --remove-all -n 57-services
----

.Template
[source,bash]
----
# Create service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden.properties | oc create -f - -n 57-services

# Delete service resources
oc process -f ocp/templates/weckdengeparden.yaml --param-file=ocp/templates/weckdengeparden..properties | oc delete -f - -n 57-services
----

=== Deploy application

.Build Configuration
[source,bash]
----
# Start build with local binary
oc start-build weckdengeparden --from-file=target/wdg-0.0.1-runner.jar --follow --wait -n 57-services
----
