## Get Challenges
GET http://localhost:8080/challenge

### Get Invalid Challenge Id
GET http://localhost:8080/challenge/7

### Get Valid Challenge Id
GET http://localhost:8080/challenge/1

### Provide no answer
POST http://localhost:8080/challenge/1/answer
Content-Type: application/json

### Provide invalid answer
POST 	http://localhost:8080/challenge/1/answer
Content-Type: application/json

{
  "jobId": "T1",
  "firstName": "TEST_john",
  "lastName": "TEST_doe",
  "email": "doe.john111@gmail.com",
  "answer": "50",
  "source": "MESSEN",
  "cv": "UGFzY2FsIFN0cmFzc2w6CiAgQXBwbGljYXRpb24gTUFuYWdlbWVudAoKLSBIZXRlcm9nZW5lIExhbmRzY2hhZnQKLQoKLSBXaWUgZEF0ZW5iYW5rZW4gdW1nZWhlbiBpbiBDbG91ZD8KLSBXaWUgd2lyZCBtaXQgVk1zIHVtZ2VnYW5nZW4KLSBXaWUgd2lyZCBJQUM/Ci0gSG9jaHZlcmbDvGdiYXJrZWl0IHdpZT8KICAtIEdyZWVuL0JsdWUgRGVwbG95bWVudAotIEJlaXNwaWVsZQogIC0gSUFDIChEb2NrZXJmaWxlcywgT0NQLURFc2NyaXB0b3IsIFNjcmlwdHMpCiAgICAtLSBSZXByb2R1Y2libGUsIFJlcGVhdGFibGUsIENvbnNpc3RlbnQsIFRydXN0YWJsZSwgQXV0b21hdGVkCiAgLSBDb250YWluZXIKICAgIC0tIFZvcnRlaWxlIE5hY2h0ZWlsZSwgV2llIGZ1bmt0aW9uaWVyZW4sIHdhcyBpc3QgYW5kZXJzLCBzdGF0ZWxlc3MvZnVsbAogIC0gT0NQCiAgICAtLSBFcndlaXRlcnQgS3ViZXJuZXRlcywgQ2hhaW5lZCBwcm9jZXNzZXMgQ0kvQ0QgSW50ZWdyYXRpb24KICAtIENJL0NEIG1pdCBKZW5raW5zIGluIE9DUAogIC0gQmFja3VwISEhIQogICAgLS0gQ0kvQ0QgT09FR0tLLiBmZWF0dXJlIGJyYW5jaGVzIC0+IGJ1aWxkL3Rlc3QvZGVwbG95L2ludGVncmF0aW9uLXRlc3QKICAgIC0tCg=="
}

###
### Provide invalid answer
#POST https://weckdengeparden-57-services-test.cloud.itandtel.at/challenge/1/answer
POST http://localhost:8080/challenge/1/answer
Content-Type: application/json

{
  "jobId": "156160",
  "firstName": "TEST_Thomas",
  "lastName": "TEST_Herzog",
  "email": "doe.john0005@gmail.com",
  "answer": "50",
  "source": "MESSEN",
  "otherSource" : "Ich will",
  "messageToGepardec" : "Ich will",
  "cv": "UGFzY2FsIFN0cmFzc2w6CiAgQXBwbGljYXRpb24gTUFuYWdlbWVudAoKLSBIZXRlcm9nZW5lIExhbmRzY2hhZnQKLQoKLSBXaWUgZEF0ZW5iYW5rZW4gdW1nZWhlbiBpbiBDbG91ZD8KLSBXaWUgd2lyZCBtaXQgVk1zIHVtZ2VnYW5nZW4KLSBXaWUgd2lyZCBJQUM/Ci0gSG9jaHZlcmbDvGdiYXJrZWl0IHdpZT8KICAtIEdyZWVuL0JsdWUgRGVwbG95bWVudAotIEJlaXNwaWVsZQogIC0gSUFDIChEb2NrZXJmaWxlcywgT0NQLURFc2NyaXB0b3IsIFNjcmlwdHMpCiAgICAtLSBSZXByb2R1Y2libGUsIFJlcGVhdGFibGUsIENvbnNpc3RlbnQsIFRydXN0YWJsZSwgQXV0b21hdGVkCiAgLSBDb250YWluZXIKICAgIC0tIFZvcnRlaWxlIE5hY2h0ZWlsZSwgV2llIGZ1bmt0aW9uaWVyZW4sIHdhcyBpc3QgYW5kZXJzLCBzdGF0ZWxlc3MvZnVsbAogIC0gT0NQCiAgICAtLSBFcndlaXRlcnQgS3ViZXJuZXRlcywgQ2hhaW5lZCBwcm9jZXNzZXMgQ0kvQ0QgSW50ZWdyYXRpb24KICAtIENJL0NEIG1pdCBKZW5raW5zIGluIE9DUAogIC0gQmFja3VwISEhIQogICAgLS0gQ0kvQ0QgT09FR0tLLiBmZWF0dXJlIGJyYW5jaGVzIC0+IGJ1aWxkL3Rlc3QvZGVwbG95L2ludGVncmF0aW9uLXRlc3QKICAgIC0tCg=="
}

###