## Logging configurations
quarkus:
  log:
    console:
      enable: true
      level: "INFO"

personio/mp-rest/scope: "javax.enterprise.context.RequestScoped"
personio/mp-rest/connectTimeout: 2000
personio/mp-rest/readTimeout: 2000
mp:
  opentracing:
    server:
      operation-name-provider: "http-path"