apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    bewerberservice:
      owner: "Gepaplexx-Demos"
      repository: "weckdengeparden"
      webhook:
        endpoint: "/push"
        port: "12000"
        method: "POST"
      events:
        - "push"
      webhookSecret:
        name: github-webhook-secret
        key: secret
      insecure: false
      active: true
    bewerberservice-ci-create:
      owner: "Gepaplexx-Demos"
      repository: "weckdengeparden-ci"
      webhook:
        endpoint: "/create"
        port: "12000"
        method: "POST"
      events:
        - "create"
      webhookSecret:
        name: github-webhook-secret
        key: secret
      insecure: false
      active: true
      contentType: "json"
    bewerberservice-ci-delete:
      owner: "Gepaplexx-Demos"
      repository: "weckdengeparden-ci"
      webhook:
        endpoint: "/delete"
        port: "12000"
        method: "POST"
      events:
        - "delete"
      webhookSecret:
        name: github-webhook-secret
        key: secret
      insecure: false
      active: true
      contentType: "json"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    controller: eventsource-controller
    eventsource-name: github
    owner-name: github
  name: github-webhook
spec:
  host: ""
  tls:
    termination: edge
  to:
    kind: ""
    name: github-eventsource-svc
    weight: null
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bewerberservice
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-bewerberservice
      eventSourceName: github
      eventName: bewerberservice
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "main"
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 20
    - template:
        name: bewerberservice-cicd-workflow-trigger
        argoWorkflow:
          parameters:
            - src:
                dependencyName: github-bewerberservice
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-bewerberservice
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github-bewerberservice
                dataKey: body.repository.name
              dest: spec.arguments.parameters.2.value
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: bewerberservice-cicd-workflow-trigger-
              spec:
                arguments:
                  parameters:
                    - name: repo
                      value: must get set from payload
                    - name: revision
                      value: must get set from payload
                    - name: reponame
                      value: must get set from payload
                entrypoint: execute-pipeline
                workflowTemplateRef:
                  name: template-java-ci-workflow
                  clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bewerberservice-ci-create-argo-application
spec:
  template:
    serviceAccountName: create-argo-application-sa
  dependencies:
    - name: github-bewerberservice
      eventSourceName: github
      eventName: bewerberservice-ci-create
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 20
    - template:
        name: create-argo-application-trigger
        k8s:
          operation: create
          parameters:
            - src:
                dependencyName: github-bewerberservice
                dataKey: body.ref
              dest: spec.source.targetRevision
            - src:
                dependencyName: github-bewerberservice
                dataTemplate: "weckdengeparden-ci-{{ .Input.body.ref }}"
              dest: metadata.name
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: gets-set-from-parameter
                namespace: openshift-gitops
                finalizers:
                  - resources-finalizer.argocd.argoproj.io
              spec:
                destination:
                  namespace: bewerberservice
                  server: https://kubernetes.default.svc
                project: default
                source:
                  path: .
                  repoURL: https://github.com/gepardec/weckdengeparden-ci
                  targetRevision: gets-set-from-parameter
                syncPolicy:
                  automated:
                    prune: true
                    selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bewerberservice-ci-delete-argo-application
spec:
  template:
    serviceAccountName: create-argo-application-sa
  dependencies:
    - name: github-bewerberservice
      eventSourceName: github
      eventName: bewerberservice-ci-delete
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 20
    - template:
        name: delete-argo-application-trigger
        k8s:
          operation: delete
          parameters:
            - src:
                dependencyName: github-bewerberservice
                dataTemplate: "weckdengeparden-ci-{{ .Input.body.ref }}"
              dest: metadata.name
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: gets-set-from-parameter
                namespace: openshift-gitops
---